# Generated by Django 3.1.5 on 2021-01-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50, verbose_name='Название')),
                ('About', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
