# Generated by Django 3.1.5 on 2021-01-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210110_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Confines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(verbose_name='Название')),
                ('About', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ограничение',
                'verbose_name_plural': 'Ограничения',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(verbose_name='Название')),
                ('Date', models.DateTimeField(verbose_name='Дата и время мероприятия')),
                ('About', models.TextField(verbose_name='Описание мероприятия')),
                ('ConfineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.confines')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(verbose_name='Название типа площадки')),
            ],
            options={
                'verbose_name': 'Тип площадки',
                'verbose_name_plural': 'Типы площадок',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.CreateModel(
            name='TicketsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllCount', models.IntegerField(verbose_name='Общее количество билетов')),
                ('SoldCount', models.IntegerField(verbose_name='Количество проданных билетов')),
                ('EvId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Кол-во билетов',
                'verbose_name_plural': 'Кол-во билетов',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Place', models.TextField(verbose_name='Место в зале')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('TicketCat', models.TextField(verbose_name='Категория билета')),
                ('EvId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='SoldTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(verbose_name='Имя покупателя')),
                ('Surname', models.TextField(verbose_name='Фамилия покупателя')),
                ('EvId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('TicketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tickets')),
            ],
            options={
                'verbose_name': 'Проданный билет',
                'verbose_name_plural': 'Проданные билеты',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(verbose_name='Название места')),
                ('About', models.TextField(verbose_name='Описание места')),
                ('Adress', models.TextField(verbose_name='Место проведения мероприятия')),
                ('CityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('TypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.placetype')),
            ],
            options={
                'verbose_name': 'Площадка проведения мероприятия',
                'verbose_name_plural': 'Площадки проведения мероприятий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='Place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.places'),
        ),
        migrations.AddField(
            model_name='event',
            name='TypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventtypes'),
        ),
    ]
