# Generated by Django 3.1.5 on 2021-01-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210110_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='Adress',
            field=models.TextField(verbose_name='Адрес проведения мероприятия'),
        ),
    ]
