# Generated by Django 3.1.5 on 2021-06-28 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_soldtickets_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldtickets',
            name='UserId',
        ),
        migrations.AddField(
            model_name='soldtickets',
            name='Buyer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
