# Generated by Django 3.1.5 on 2021-06-28 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20210628_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldtickets',
            name='Buyer',
            field=models.ForeignKey(db_column='Buyer', default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
