# Generated by Django 3.1.5 on 2021-06-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210628_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldtickets',
            name='Buyer',
        ),
    ]
