# Generated by Django 3.1.5 on 2021-06-28 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_remove_soldtickets_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldtickets',
            name='Buyer',
            field=models.ForeignKey(db_column='Buyer', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
